# Generated by Django 3.1.4 on 2021-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20210116_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subdesc',
            field=models.TextField(default='default.jpg'),
            preserve_default=False,
        ),
    ]
